### ISSUE TITLE
How do I compile properly? My compilation gives an error on start

### ISSUE THREAD

**Issue by aepic999** [jvyden/jvyterm#3]
I compiled this with CSC using the command line. This is my command:
`C:\Windows\Microsoft.NET\Framework\v4.0.30319\csc.exe /out:jvyterm.exe /t:exe *.cs`
Upon trying to run my compiled version of jvyterm, I get this error:
```Unhandled Exception: System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "jvyterm.lang.resources" was correctly embedded or linked into assembly "jvyterm" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at jvyterm.lang.get_init()
   at jvyterm.Program.init()
   at jvyterm.Program.Main()```

**Comment by jvyden** [comment]
Looks like something to do with the lang.resx file. Can you compile properly in Visual Studio?

**Comment by jvyden** [comment]
Actually, it looks like your .NET Framework is out of date. The minimum version is 4.6.1, however this may change in the future.

**Comment by aepic999** [comment]
I know I need to attach the resources file in some way, but how would I do that in CSC? I can't install Visual Studio on this PC, because it has 32GB of storage.
If there is no way, can I have a pre-compiled EXE file?
(This was part of the original message, but GitHub is being a shit and not even wanting to include everything)

**Comment by jvyden** [comment]
I can make a release, however I can not guarantee that it will work properly under 4.0. You'll have to give it a shot.

**Comment by aepic999** [comment]
My compiler says "Microsoft (R) Visual C# Compiler version 4.7.2542.1" btw.

**Comment by jvyden** [comment]
Its probably not the compiler, its probably the framework version. What is the absolute latest version do you have?

**Comment by aepic999** [comment]
A few other file's versions are 4.7.2542.1, so I think that's the framework version.
It's a problem with the resources, I think.

**Comment by jvyden** [comment]
1.0 has been released, see if that works.

**Comment by jvyden** [comment]
Solution for googlers: Use MSBuild instead of CSC for .sln projects.
