### ISSUE TITLE
1.0 fails to move BasicCommands to plugins folder

### ISSUE THREAD

**Issue by jvyden** [jvyden/jvyterm#4]
**Explain what went wrong, or what your feature request is**
When starting 1.0 for the first time, the application attempts to move all dlls in its current location to the plugins folder after making it. This does not succeed.
**Include logs if possible**
```
Initializing...
First run, prepping...

Unhandled Exception: System.IO.DirectoryNotFoundException: Could not find a part
 of the path 'D:\User Files\Desktop\jvyterm\data\plugins\'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalCopy(String sourceFileName, String destFileName, Boolean overwrite, Boolean checkHost)
   at System.IO.FileInfo.CopyTo(String destFileName)
   at jvyterm.onFirstRun.prep(String f)
   at jvyterm.Program.firstrun()
   at jvyterm.Program.init()
   at jvyterm.Program.Main()
```

**Comment by jvyden** [comment]
Solved.

**Comment by jvyden** [comment]
Solution for googlers: Make sure you added a file name after the path.
